// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluqc4qr8bwUyBkoR7YZXAQjhzg_cD1EM',
    appId: '1:574820817153:web:53e3553bc099b4d20e2300',
    messagingSenderId: '574820817153',
    projectId: 'moviehaven-4d1f5',
    authDomain: 'moviehaven-4d1f5.firebaseapp.com',
    storageBucket: 'moviehaven-4d1f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG54Ic6eV8oRcPJaj1ZEKLM2MtEgKbZKI',
    appId: '1:574820817153:android:704216bf9b20ee860e2300',
    messagingSenderId: '574820817153',
    projectId: 'moviehaven-4d1f5',
    storageBucket: 'moviehaven-4d1f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQTM53XGy72q5OuYiu4Pk54LbtbVRnoJg',
    appId: '1:574820817153:ios:e31cc7557d8f9a910e2300',
    messagingSenderId: '574820817153',
    projectId: 'moviehaven-4d1f5',
    storageBucket: 'moviehaven-4d1f5.firebasestorage.app',
    iosBundleId: 'com.example.movieHaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQTM53XGy72q5OuYiu4Pk54LbtbVRnoJg',
    appId: '1:574820817153:ios:e31cc7557d8f9a910e2300',
    messagingSenderId: '574820817153',
    projectId: 'moviehaven-4d1f5',
    storageBucket: 'moviehaven-4d1f5.firebasestorage.app',
    iosBundleId: 'com.example.movieHaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAluqc4qr8bwUyBkoR7YZXAQjhzg_cD1EM',
    appId: '1:574820817153:web:e85af78207aff25e0e2300',
    messagingSenderId: '574820817153',
    projectId: 'moviehaven-4d1f5',
    authDomain: 'moviehaven-4d1f5.firebaseapp.com',
    storageBucket: 'moviehaven-4d1f5.firebasestorage.app',
  );
}
